ekf_node:
  ros__parameters:
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom
    publish_tf: true
    two_d_mode: true
    use_sim_time: true

    frequency: 50.0

    odom0: odom
    odom0_config: [true, true, false,
                  false, false, true,
                  true, true, false,
                  false, false, true,
                  false, false, false]
    odom0_differential: false
    odom0_queue_size: 10